import type { Project, Skill } from '@/lib/types';

export const skills: Skill[] = [
  {
    name: 'AutoCAD',
    imageUrl: 'https://placehold.co/100x100.png',
  },
  {
    name: 'Revit',
    imageUrl: 'https://placehold.co/100x100.png',
  },
  {
    name: 'SolidWorks',
    imageUrl: 'https://placehold.co/100x100.png',
  },
  {
    name: '3D Rendering',
    imageUrl: 'https://placehold.co/100x100.png',
  },
  {
    name: 'Blueprint',
    imageUrl: 'https://placehold.co/100x100.png',
  },
];

export const initialProjects: Project[] = [
  {
    id: 'proj1',
    title: 'Pertamina Spatial Data Collection (2013)',
    description: 'Managed the collection of technical spatial data for Pertamina\'s critical infrastructure projects.',
    url: '#',
    interactions: 250,
    tags: ['Pertamina', 'Spatial Data', 'Data Collection'],
    imageUrl: 'https://placehold.co/600x400.png',
    logoUrl: 'https://placehold.co/100x40.png',
  },
  {
    id: 'proj2',
    title: 'Ultimate Java Backbone Fiber Optic Project (2014)',
    description: 'Played a key role in the engineering and drafting for the Regional 2 Ultimate Java Backbone fiber optic network.',
    url: '#',
    interactions: 240,
    tags: ['Fiber Optic', 'Telecommunications', 'Infrastructure'],
    imageUrl: 'https://placehold.co/600x400.png',
    logoUrl: 'https://placehold.co/100x40.png',
  },
  {
    id: 'proj3',
    title: 'RS Indriati Solo - Building Automation (2016)',
    description: 'Designed and drafted the complete Building Automation System (BAS) for Indriati Hospital in Solo.',
    url: '#',
    interactions: 220,
    tags: ['Building Automation', 'Hospital', 'BMS'],
    imageUrl: 'https://placehold.co/600x400.png',
    logoUrl: 'https://placehold.co/100x40.png',
  },
  {
    id: 'proj4',
    title: 'JW Marriott Yogyakarta - Building Automation (2017)',
    description: 'Developed the building automation blueprints for the luxury JW Marriott Hotel in Yogyakarta.',
    url: '#',
    interactions: 215,
    tags: ['Building Automation', 'Hotel', 'BMS'],
    imageUrl: 'https://placehold.co/600x400.png',
    logoUrl: 'https://placehold.co/100x40.png',
  },
  {
    id: 'proj5',
    title: 'RS Harapan Kita Jakarta - Building Automation (2017)',
    description: 'Engineered the comprehensive building automation plans for the renowned Harapan Kita Hospital in Jakarta.',
    url: '#',
    interactions: 180,
    tags: ['Building Automation', 'Hospital', 'BMS'],
    imageUrl: 'https://placehold.co/600x400.png',
    logoUrl: 'https://placehold.co/100x40.png',
  },
  {
    id: 'proj6',
    title: 'Hotel Mercure Batavia Jakarta - Building Automation (2017)',
    description: 'Oversaw the drafting and design for the BAS implementation at the historic Hotel Mercure Batavia in Jakarta.',
    url: '#',
    interactions: 170,
    tags: ['Building Automation', 'Hotel', 'BMS'],
    imageUrl: 'https://placehold.co/600x400.png',
    logoUrl: 'https://placehold.co/100x40.png',
  },
  {
    id: 'proj7',
    title: 'RS Eka Hospital Cibubur - Building Automation (2018)',
    description: 'Led the drafting team for the advanced building automation system at Eka Hospital, Cibubur.',
    url: '#',
    interactions: 190,
    tags: ['Building Automation', 'Hospital', 'BMS'],
    imageUrl: 'https://placehold.co/600x400.png',
    logoUrl: 'https://placehold.co/100x40.png',
  },
  {
    id: 'proj8',
    title: 'RS Eka Hospital Bekasi - Building Automation (2018)',
    description: 'Created detailed blueprints and schematics for the BAS at Eka Hospital\'s Bekasi facility.',
    url: '#',
    interactions: 195,
    tags: ['Building Automation', 'Hospital', 'BMS'],
    imageUrl: 'https://placehold.co/600x400.png',
    logoUrl: 'https://placehold.co/100x40.png',
  },
  {
    id: 'proj9',
    title: 'Swiss-Belhotel Solo - Building Automation (2019)',
    description: 'Managed the building automation system design and drafting for the modern Swiss-Belhotel in Solo.',
    url: '#',
    interactions: 160,
    tags: ['Building Automation', 'Hotel', 'BMS'],
    imageUrl: 'https://placehold.co/600x400.png',
    logoUrl: 'https://placehold.co/100x40.png',
  },
  {
    id: 'proj10',
    title: 'PLN SCADA Facility Upgrade (Banten) (2023)',
    description: 'Led the technical drafting for the upgrade of SCADA system facilities at a PLN Hub Substation in Banten.',
    url: '#',
    interactions: 150,
    tags: ['SCADA', 'PLN', 'Electrical Grid', 'Upgrade'],
    imageUrl: 'https://placehold.co/600x400.png',
    logoUrl: 'https://placehold.co/100x40.png',
  },
  {
    id: 'proj11',
    title: 'PLN SCADA Facility Installation (Banten) (2024)',
    description: 'Involved in the installation of new SCADA system facilities at a PLN Hub Substation in the Banten region.',
    url: '#',
    interactions: 140,
    tags: ['SCADA', 'PLN', 'Electrical Grid', 'Installation'],
    imageUrl: 'https://placehold.co/600x400.png',
    logoUrl: 'https://placehold.co/100x40.png',
  },
  {
    id: 'proj12',
    title: 'PLN SCADA Facility Installation (Banten) (2024)',
    description: 'Managed the drafting and documentation for the installation of new SCADA facilities at a PLN Hub Substation.',
    url: '#',
    interactions: 135,
    tags: ['SCADA', 'PLN', 'Electrical Grid', 'Installation'],
    imageUrl: 'https://placehold.co/600x400.png',
    logoUrl: 'https://placehold.co/100x40.png',
  },
];
